# Generated by Django 3.2.6 on 2021-09-23 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('options', models.ManyToManyField(related_name='productvariation', to='store.Option')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productvariation', to='store.product')),
            ],
        ),
    ]
