# Generated by Django 3.2.6 on 2021-09-23 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_productvariantion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductVariantion',
            new_name='ProductVariation',
        ),
    ]
