# Generated by Django 3.2.6 on 2021-09-23 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_attributevalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributevalue',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='attributevalue', to='store.product'),
            preserve_default=False,
        ),
    ]
