# Generated by Django 3.2.6 on 2021-09-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_product_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='variants',
            field=models.ManyToManyField(related_name='productvariation', to='store.Variant'),
        ),
    ]
