# Generated by Django 3.2.6 on 2021-09-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_productvariation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariation',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
