# Generated by Django 3.2.6 on 2021-10-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_vendor_due_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='due_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
