# Generated by Django 3.2.6 on 2021-09-27 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_productvariation_stock'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='productvariation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.productvariation'),
            preserve_default=False,
        ),
    ]
