# Generated by Django 3.2.6 on 2021-09-30 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cartitems',
            new_name='ordereditems',
        ),
    ]
