# Generated by Django 3.2.6 on 2021-09-30 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_productvariation_stock'),
        ('cart', '0004_rename_cartitems_order_ordereditems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordereditems',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.order')),
                ('productvariation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productvariation')),
            ],
        ),
    ]
