# Generated by Django 3.2.6 on 2021-10-03 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_productvariation_stock'),
        ('cart', '0012_auto_20211003_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='productvariation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.productvariation'),
        ),
    ]
